### ISSUE TITLE
when use in ubuntu it error

### ISSUE THREAD

**Issue by buzai** [SuperID/super-queue#34]
node v7 , ubuntu16 , redis 3.0.2
Error: please call push() method after `start` event
    at Producer.push (/mydata/code/test/node_modules/_super-queue@0.1.0@super-queue/lib/producer.js:139:23)
    at Object.<anonymous> (/mydata/code/test/Producer.js:19:3)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.runMain (module.js:605:10)
    at run (bootstrap_node.js:427:7)
    at startup (bootstrap_node.js:151:9)
    at bootstrap_node.js:542:3
start working
Unhandled rejection Error: Connection is closed.
    at /mydata/code/test/node_modules/_ioredis@2.5.0@ioredis/lib/connectors/connector.js:38:16
    at _combinedTickCallback (internal/process/next_tick.js:73:7)
    at process._tickCallback (internal/process/next_tick.js:104:9)
    at Module.runMain (module.js:607:11)
    at run (bootstrap_node.js:427:7)
    at startup (bootstrap_node.js:151:9)
    at bootstrap_node.js:542:3

**Comment by leizongmin** [comment]
```javascript
const p = new Prosucer();
p.on('start', () => {
  // call push() after "start" event
  p.push(data);
});
```

**Comment by buzai** [comment]
@leizongmin thank u
